package gov.nist.healthcare.tools.hl7.v2.igamt.lite.domain;

public class BindingExportConfig {

	private boolean includeForDatatype =true;;
	private boolean includeForAutoGeneratedDatatype =true;
	private boolean includeForSegment=true;
	private boolean includeForAutoGeneratedSegments=true;
	private boolean includeForMessage=true;
	private boolean includeForCompositeProfile=true;
	private boolean location=true;
	private boolean valueSetId= true;
	private boolean valueSetName = true;
	private boolean bindingStrength=false;
	private boolean bindingLocation= false;
	private boolean singleCode= true;
	private boolean singleCodeSystem =false;
	
	public boolean isIncludeForDatatype() {
		return includeForDatatype;
	}
	public void setIncludeForDatatype(boolean includeForDatatype) {
		this.includeForDatatype = includeForDatatype;
	}
	public boolean isIncludeForAutoGeneratedDatatype() {
		return includeForAutoGeneratedDatatype;
	}
	public void setIncludeForAutoGeneratedDatatype(boolean includeForAutoGeneratedDatatype) {
		this.includeForAutoGeneratedDatatype = includeForAutoGeneratedDatatype;
	}
	public boolean isIncludeForSegment() {
		return includeForSegment;
	}
	public void setIncludeForSegment(boolean includeForSegment) {
		this.includeForSegment = includeForSegment;
	}
	public boolean isIncludeForAutoGeneratedSegments() {
		return includeForAutoGeneratedSegments;
	}
	public void setIncludeForAutoGeneratedSegments(boolean includeForAutoGeneratedSegments) {
		this.includeForAutoGeneratedSegments = includeForAutoGeneratedSegments;
	}
	public boolean isIncludeForMessage() {
		return includeForMessage;
	}
	public void setIncludeForMessage(boolean includeForMessage) {
		this.includeForMessage = includeForMessage;
	}
	public boolean isIncludeForCompositeProfile() {
		return includeForCompositeProfile;
	}
	public void setIncludeForCompositeProfile(boolean includeForCompositeProfile) {
		this.includeForCompositeProfile = includeForCompositeProfile;
	}
	public boolean isLocation() {
		return location;
	}
	public void setLocation(boolean location) {
		this.location = location;
	}
	public boolean isValueSetId() {
		return valueSetId;
	}
	public void setValueSetId(boolean valueSetId) {
		this.valueSetId = valueSetId;
	}
	public boolean isValueSetName() {
		return valueSetName;
	}
	public void setValueSetName(boolean valueSetName) {
		this.valueSetName = valueSetName;
	}
	public boolean isBindingStrength() {
		return bindingStrength;
	}
	public void setBindingStrength(boolean bindingStrength) {
		this.bindingStrength = bindingStrength;
	}
	public boolean isBindingLocation() {
		return bindingLocation;
	}
	public void setBindingLocation(boolean bindingLocation) {
		this.bindingLocation = bindingLocation;
	}
	public boolean isSingleCode() {
		return singleCode;
	}
	public void setSingleCode(boolean singleCode) {
		this.singleCode = singleCode;
	}
	public boolean isSingleCodeSystem() {
		return singleCodeSystem;
	}
	public void setSingleCodeSystem(boolean singleCodeSystem) {
		this.singleCodeSystem = singleCodeSystem;
	}
	
	
	
	
	
	
}
