package gov.nist.healthcare.tools.hl7.v2.igamt.lite.domain;

public class IncludeAutoGenerated {
	
	public boolean datatype=false;
	public boolean segment=false;
	public boolean coConstraints=false;
	public boolean dynamicMapping=false;
	public boolean preDef=false;
	public boolean postDef=false;
	public boolean comments=false;
	public boolean predicates=false;
	public boolean conformanceStatements=false;
	public boolean purposeAndUse=false;
	public boolean usageNotes=false;
	public boolean binding=false;
	public boolean comment=false;
	public boolean definitionText = false;

}
