package gov.nist.healthcare.tools.hl7.v2.igamt.lite.domain;

public class IncludeAutoGenerated {
	
	public boolean datatype=false;
	public boolean segment=false;
	public boolean coConstraints=false;

}
